acount/urls.py
from django.urls import path
from .views import ArticleListView, ArticleCreateView, ArticleUpdateView, DeleteArticleView, ProfileView

app_name = 'accounts'

urlpatterns = [
    path('', ArticleListView.as_view(), name='home'),
    path ('article/create/', ArticleCreateView.as_view(), name='article_create'),
    path ('article/update/<int:pk>/', ArticleUpdateView.as_view(), name='article_update'),
    path ('article/delete/<int:pk>/', DeleteArticleView.as_view(), name='article_delete'),
    path ('profile/', ProfileView.as_view(), name='profile'),
]

blog/urls.py
from django.urls import path
from .views import ArticleListView, ArticleDetailView, ArticleCategoryView, AuthorArticleListView, ArticlePreviewView, SearchListView

app_name = 'blog'
urlpatterns = [
    path('', ArticleListView.as_view(), name = 'home'),
    path('article/<slug:slug>/', ArticleDetailView.as_view(), name = 'single'),
    path('category/<slug:slug>/', ArticleCategoryView.as_view(), name = 'category'),
    path('Author/<slug:username>/', AuthorArticleListView.as_view(), name = 'author'),
    path('search/', SearchListView.as_view(), name = 'search'),
    path('search/page/<int:page>', SearchListView.as_view(), name = 'search'),
    path('preview/<int:pk>/', ArticlePreviewView.as_view(), name = 'preview'),
]

jam/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from acount.views import Login, signup, activate

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', Login.as_view(), name='login'),
    path('', include('django.contrib.auth.urls')),
    path('signup/', signup, name='signup'),
    path('activate/<uidb64>/<token>/', activate, name='activate'),
    path('blog/', include('blog.urls')),
    path('', include('website.urls')),
    path('accounts/', include('acount.urls')),
    path('comment/', include('comment.urls')),
    re_path(r'^ratings/', include('star_ratings.urls', namespace='ratings')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path
from .views import web_home, ContactsView, AboutView, Newsletter

app_name = 'website'
urlpatterns = [
    path('', web_home, name = 'web_home'),
    path('contact/', ContactsView.as_view(), name = 'contact'),
    path('about/', AboutView, name = 'about'),
    path('Newsletter/', Newsletter, name = "Newsletter" ),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.utils.html import format_html
from acount.models import User
import uuid
from django.contrib.contenttypes.fields import GenericRelation
from comment.models import Comment

# create a manager.
class ArticleManager(models.Manager):
    def published(self):
        return self.filter(status='p')

class CategoryManager(models.Manager):
    def activ_cat(self):
        return self.filter(is_active=True)


class IpAddress(models.Model):
    ip_address = models. GenericIPAddressField()


class Category(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, unique=True)
    parent = models.ForeignKey('self', on_delete=models.SET_NULL, null=True, blank=True, related_name='children')
    is_active = models.BooleanField(default=True)
    position = models.PositiveIntegerField()

    def __str__(self):
        return self.title
    
    def active_category(self):
        return Category.objects.filter(is_active=True)
    
    def get_absolute_url(self):
        return "/blog/category/{}/".format(self.slug)
    
    objects = CategoryManager()

class Article(models.Model):
    STATUS_CHOICES = (
        ('d', 'Draft'),
        ('p', 'Publish'),
        ('i', 'investigation'),
        ('r', 'rejected'),
    )
    title = models.CharField(max_length = 255)
    Author = models.ForeignKey(User, null=True ,on_delete=models.SET_NULL, related_name='articles')
    slug = models.SlugField(max_length = 255, unique = True, default = uuid.uuid4)
    category = models.ManyToManyField(Category, related_name='articles')
    thumbnail = models.ImageField(upload_to = "images")
    description = models.TextField()
    created_date = models.DateTimeField(auto_now_add = True)
    updated_date = models.DateTimeField(auto_now = True)
    published_date = models.DateTimeField(default = timezone.now)
    is_special = models.BooleanField(default=False)
    status = models.CharField(max_length = 1, choices = STATUS_CHOICES)
    comments = GenericRelation(Comment)
    hits = models.ManyToManyField(IpAddress, through="ArticleHits", blank=True, related_name='hits')

    def __str__(self):
        return self.title

    def active_category(self):
        return self.category.filter(is_active=True)

    objects = ArticleManager()

    def Category_to_string(self):
        return ", ".join([str(title) for title in self.active_category()])

    def thumbnail_tag(self):
        return format_html("<img width=100 height=75 style='border-radius: 10px'; src='{}'/>".format(self.thumbnail.url))

    thumbnail_tag.short_description = 'Thumbnail'
    thumbnail_tag.allow_tags = True

class ArticleHits(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    ip_address = models.ForeignKey(IpAddress, on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)

blog/views.py
from acount.models import User
from .models import Article, Category
from django.shortcuts import get_object_or_404
from acount.mixins import AuthorEditAccessMixin
from django.views.generic import ListView, DetailView


#def home(request):
#    articles = Article.objects.published()
#    paginator = Paginator(articles, 1)
#    page = request.GET.get('page')
#    articles = paginator.get_page(page)
#    context = {'Articles': articles}
#    return render(request, 'blog/blog.html', context)
 

class ArticleListView(ListView):
    model = Article
    template_name = 'blog/blog.html'
    context_object_name = 'Articles'
    paginate_by = 5

    def get_queryset(self):
        return Article.objects.published()


class SearchListView(ListView):
    model = Article
    template_name = 'blog/search.html'
    context_object_name = 'Articles'
    paginate_by = 5

    def get_queryset(self):
        search = self.request.GET.get('q')
        if search:
            object_list = Article.objects.filter(description__icontains=search)
        else:
            object_list = self.model.objects.none()
        return object_list

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['search'] = self.request.GET.get('q')
        return context
  
  
#def blog_single(request, slug):
#    article = get_object_or_404(Article.objects.published(), slug = slug)
#    context = {'Article': article}
#    return render(request, 'blog/blog-single.html', context)


class ArticleDetailView(DetailView):
    model = Article
    template_name = 'blog/blog-single.html'
    context_object_name = 'Article'

    def get_object(self):
        slug = self.kwargs.get('slug')
        article = get_object_or_404(Article.objects.published(), slug = slug)
        
        ip_address = self.request.user.ip_address
        if ip_address not in article.hits.all():
            article.hits.add(ip_address)
            article.save()

        return article


class ArticlePreviewView(AuthorEditAccessMixin, DetailView):
    model = Article
    template_name = 'blog/blog-single.html'
    context_object_name = 'Article'

    def get_object(self):
        pk = self.kwargs.get('pk')
        return get_object_or_404(Article, pk = pk)


#def blog_category(request, slug):
#    category = get_object_or_404(Category, slug = slug)
#    articles = Article.objects.filter(category = category, status= 'p')
#    paginator = Paginator(articles, 1)
#    page = request.GET.get('page')
#    articles = paginator.get_page(page)
#    context = {'Category': category, 'Articles': articles}
#    return render(request, 'blog/blog-category.html', context)


class ArticleCategoryView(ListView):
    model = Article
    template_name = 'blog/blog-category.html'
    context_object_name = 'Articles'
    paginate_by = 1

    def get_queryset(self):
        global category
        slug = self.kwargs.get('slug')
        category = get_object_or_404(Category, slug = slug)
        return Article.objects.filter(category = category, status= 'p')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['Category'] = category
        return context


class AuthorArticleListView(ListView):
    model = Article
    template_name = 'blog/blog-author.html'
    context_object_name = 'Articles'
    paginate_by = 1
    def get_queryset(self):
        global author
        author = get_object_or_404(User, username = self.kwargs.get('username'))
        return Article.objects.filter(Author = author, status= 'p')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['Author'] = author
        return context

templates/blog/base.html
{% load static %}
{% load blog_tags %}
{% load ratings %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Blog</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'img/favicon.png' %}" rel="icon">
  <link href="{% static 'img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Roboto:300,300i,400,400i,500,500i,700,700i&display=swap" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'vendor/animate.css/animate.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">
  <!---star rating section-->
  <link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">
  <script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>

  <!-- Template Main CSS File -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet">

  <!-- =======================================================
  * Template Name: Moderna - v4.7.0
  * Template URL: https://bootstrapmade.com/free-bootstrap-template-corporate-moderna/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top d-flex align-items-center ">
    <div class="container d-flex justify-content-between align-items-center">

      <div class="logo" style="color:red;">
      {% block title %}{% title %}{% endblock title %}
        {% if user.is_authenticated %}
          <a href="{% url 'logout' %}" style="color:white; ml:10px;">Logout</a>
          <a href="{% url 'accounts:profile' %}" style="color:white; ml:10px;">{{request.user.get_full_name}}</a>
        {% else %}
          <a href="{% url 'login' %}" style="color:white; ml:10px;">Login</a>
        {% endif %}
      </div>

      <nav id="navbar" class="navbar">
        <ul>
          <li><a class="" href="{% url 'website:web_home' %}">Home</a></li>
          <li><a href="{% url 'website:about' %}">About</a></li>
          <li><a class="active" href="{% url 'blog:home' %}">Blog</a></li>
          <li><a href="{% url 'website:contact' %}">Contact</a></li>
          <li><a href="{% url 'accounts:profile' %}">Go to profile</a></li>
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->

    </div>
  </header><!-- End Header -->
  {% block content %}
    
  {% endblock content %}
  <!-- ======= Footer ======= -->
  <footer id="footer" data-aos="fade-up" data-aos-easing="ease-in-out" data-aos-duration="500">

    <div class="footer-newsletter">
      <div class="container">
        <div class="row">
          <div class="col-lg-6">
            <h4>Our Newsletter</h4>
            <p>Inter your email here for newsletter. </p>
          </div>
          <div class="col-lg-6">
            <form action="{% url 'website:Newsletter' %}" method="post">
              {% csrf_token %}
              <input type="email" name="email"><input type="submit" value="Subscribe">
            </form>
          </div>
        </div>
      </div>
    </div>

    <div class="footer-top">
      <div class="container">
        <div class="row">

          <div class="col-lg-3 col-md-6 footer-links">
            <h4>Useful Links</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'website:web_home' %}">Home</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'website:about' %}">About Me</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'website:contact' %}">Contact Me</a></li>
            </ul>
          </div>

          <div class="col-lg-3 col-md-6 footer-links">
            <h4>Our Services</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Web Design</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Web Development</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Product Management</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Marketing</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Graphic Design</a></li>
            </ul>
          </div>

          <div class="col-lg-3 col-md-6 footer-contact">
            <h4>Contact Me</h4>
            <p>
              Khorasan <br>
              Quchan<br>
              Khaabgaah khaarazmi <br><br>
              <strong>Phone:</strong> 09334580660<br>
              <strong>Email:</strong> Hamzehosseiny@gmail.com<br>
            </p>

          </div>

          <div class="col-lg-3 col-md-6 footer-info">
            <p></p>

          </div>

        </div>
      </div>
    </div>

    <div class="container">
      <div class="copyright">
        &copy; Copyright <strong><span>Moderna</span></strong>. All Rights Reserved
      </div>
      <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you purchased the pro version. -->
        <!-- Licensing information: https://bootstrapmade.com/license/ -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/free-bootstrap-template-corporate-moderna/ -->
        Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
      </div>
    </div>
  </footer><!-- End Footer -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'vendor/aos/aos.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'vendor/php-email-form/validate.js' %}"></script>
  <script src="{% static 'vendor/purecounter/purecounter.js' %}"></script>
  <script src="{% static 'vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'vendor/waypoints/noframework.waypoints.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'js/main.js' %}"></script>

</body>

</html>

templates/blog/blog-author.html
{% extends 'blog/base.html' %}
{% load static %}
{% load humanize %}

{% block content %}
    <main id="main">
    <!-- ======= Blog Section ======= -->
    <section class="breadcrumbs">
      <div class="container">

        <div class="d-flex justify-content-between align-items-center">
          <h2>blog</h2>

          <ol>
            <li><a href="{% url 'blog:home' %}">Home</a></li>
            <li>Blog</li>
          </ol>
        </div>

      </div>
    </section><!-- End Blog Section -->

    <!-- ======= Blog Section ======= -->
    <section id="blog" class="blog">
      <div class="container" data-aos="fade-up">

        <div class="row">

          <div class="col-lg-8 entries">
            {% for Article in Articles %}
            <article class="entry">
              <div class="entry-img">
                <img src="{{Article.thumbnail.url}}" alt="" class="img-fluid">
              </div>
              <h2 class="entry-title">
                <a href="{% url 'blog:single' slug=Article.slug %}">{{ Article.title }}</a>
              </h2>
              <div class="entry-meta">
                <ul>
                  <li class="d-flex align-items-center"><i class="bi bi-person"></i> <a href="{% url 'blog:author' username=Article.Author.username %}">{{Article.Author.get_full_name}}</a></li>
                  <li class="d-flex align-items-center"><i class="bi bi-clock"></i> <a href="#"><time datetime="2020-01-01">{{ Article.created_date|naturaltime }}</time></a></li>
                  <li class="d-flex align-items-center"><i class="bi bi-chat-dots"></i> <a href="#">views: {{Article.hits.count}}</a></li>
                </ul>
              </div>
              <div class="entry-content">
                <p>
                  {{ Article.description|safe }}
                </p>
                <div class="read-more">
                  <a href="{% url 'blog:single' slug=Article.slug %}">Read More</a>
                </div>
              </div>
              {% for cat in Article.category.activ_cat %}
                <a href="{% url 'blog:category' slug=cat.slug %}"><div style="text-align-last: left;">#{{cat.title}}</div></a>
              {% endfor %}
            </article>
            {% endfor %}
            <div class="blog-pagination">
              <ul class="justify-content-center">
                {% if page_obj.has_previous %}
                <li><a href="{% url 'blog:author' Author.username %}?page={{page_obj.previous_page_number}}">&lt;</a></li>
                {% endif %}
                {% for i in page_obj.paginator.page_range %}
                {% if page_obj.number == i %}
                  <li class="active"><a href="?page={{i}}">{{i}}</a></li>
                {% else %}
                  <li><a href="?page={{i}}">{{i}}</a></li>
                {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                <li><a href="{% url 'blog:author' Author.username %}?page={{page_obj.next_page_number}}">&gt;</a></li>
                {% endif %}
              </ul>
            </div>
          </div><!-- End blog entries list -->

          {% include 'blog/sidebar.html' %}
          <!-- End blog sidebar -->

        </div>

      </div>
    </section><!-- End Blog Section -->

  </main>
{% endblock content %}

templates/blog/blog-category.html
{% extends 'blog/base.html' %}
{% load static %}
{% load humanize %}

{% block content %}
    <main id="main">
    <!-- ======= Blog Section ======= -->
    <section class="breadcrumbs">
      <div class="container">

        <div class="d-flex justify-content-between align-items-center">
          <h2>Blog</h2>

          <ol>
            <li><a href="index.html">Home</a></li>
            <li>Blog</li>
          </ol>
        </div>

      </div>
    </section><!-- End Blog Section -->

    <!-- ======= Blog Section ======= -->
    <section id="blog" class="blog">
      <div class="container" data-aos="fade-up">

        <div class="row">

          <div class="col-lg-8 entries">
            {% for Article in Articles %}
            <article class="entry">
              <div class="entry-img">
                <img src="{{Article.thumbnail.url}}" alt="" class="img-fluid">
              </div>
              <h2 class="entry-title">
                <a href="{% url 'blog:single' slug=Article.slug %}">{{ Article.title }}</a>
              </h2>
              <div class="entry-meta">
                <ul>
                  <li class="d-flex align-items-center"><i class="bi bi-person"></i> <a href="{% url 'blog:author' username=Article.Author.username %}">{{Article.Author.get_full_name}}</a></li>
                  <li class="d-flex align-items-center"><i class="bi bi-clock"></i> <a href="#"><time datetime="2020-01-01">{{ Article.created_date|naturaltime }}</time></a></li>
                  <li class="d-flex align-items-center"><i class="bi bi-chat-dots"></i> <a href="#">views: {{Article.hits.count}}</a></li>
                </ul>
              </div>
              <div class="entry-content">
                <p>
                  {{ Article.description }}
                </p>
                <div class="read-more">
                  <a href="{% url 'blog:single' slug=Article.slug %}">Read More</a>
                </div>
              </div>
              {% for cat in Article.category.activ_cat %}
                <a href="{% url 'blog:category' slug=cat.slug %}"><div style="text-align-last: left;">#{{cat.title}}</div></a>
              {% endfor %}
            </article>
            {% endfor %}
            <div class="blog-pagination">
              <ul class="justify-content-center">
                {% if page_obj.has_previous %}
                <li><a href="{% url 'blog:category' slug=Category.slug %}?page={{page_obj.previous_page_number}}">&lt;</a></li>
                {% endif %}
                {% for i in page_obj.paginator.page_range %}
                {% if page_obj.number == i %}
                  <li class="active"><a href="?page={{i}}">{{i}}</a></li>
                {% else %}
                  <li><a href="?page={{i}}">{{i}}</a></li>
                {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                <li><a href="{% url 'blog:category' slug=Category.slug %}?page={{page_obj.next_page_number}}">&gt;</a></li>
                {% endif %}
              </ul>
            </div>
          </div><!-- End blog entries list -->

          {% include 'blog/sidebar.html' %}
          <!-- End blog sidebar -->

        </div>

      </div>
    </section><!-- End Blog Section -->

  </main>
{% endblock content %}

templates/blog/blog.html
{% extends 'blog/base.html' %}
{% load static %}
{% load humanize %}

{% block content %}
    <main id="main">
    <!-- ======= Blog Section ======= -->
    <section class="breadcrumbs">
      <div class="container">

        <div class="d-flex justify-content-between align-items-center">
          <h2>Blog</h2>

          <ol>
            <li><a href="{% url 'website:web_home' %}">Home</a></li>
            <li>Blog</li>
          </ol>
        </div>

      </div>
    </section><!-- End Blog Section -->

    <!-- ======= Blog Section ======= -->
    <section id="blog" class="blog">
      <div class="container" data-aos="fade-up">

        <div class="row">

          <div class="col-lg-8 entries">
            {% for Article in Articles %}
            <article class="entry">

              <div class="entry-img">
                <img src="{{Article.thumbnail.url}}" alt="" class="img-fluid">
              </div>

              <h2 class="entry-title">
                <a href="{% url 'blog:single' slug=Article.slug %}">{{ Article.title }}</a>
                {% if Article.is_special %}
                  <span class="badge badge-danger">Special</span>
                {% endif %}
              </h2>

              <div class="entry-meta">
                <ul>
                  <li class="d-flex align-items-center"><i class="bi bi-person"></i> <a href="{% url 'blog:author' username=Article.Author.username %}">{{Article.Author.get_full_name}}</a></li>
                  <li class="d-flex align-items-center"><i class="bi bi-clock"></i> <a href="#"><time datetime="2020-01-01">{{ Article.created_date|naturaltime }}</time></a></li>
                  <li class="d-flex align-items-center"><i class="bi bi-chat-dots"></i> <a href="#">views: {{Article.hits.count}}</a></li>
                </ul>
              </div>

              <div class="entry-content">
                <p>
                  {{ Article.description|safe }}
                </p>
                <div class="read-more">
                  <a href="{% url 'blog:single' slug=Article.slug %}">Read More</a>
                </div>
              </div>
              {% for cat in Article.category.activ_cat %}
                <a href="{% url 'blog:category' slug=cat.slug %}"><div style="text-align-last: left;">#{{cat.title}}</div></a>
              {% endfor %}
            </article>
            {% endfor %}
            <div class="blog-pagination">
              <ul class="justify-content-center">
                {% if page_obj.has_previous %}
                <li><a href="{% url 'blog:home' %}?page={{page_obj.previous_page_number}}">&lt;</a></li>
                {% endif %}
                {% for i in page_obj.paginator.page_range %}
                {% if page_obj.number == i %}
                  <li class="active"><a href="?page={{i}}">{{i}}</a></li>
                {% else %}
                  <li><a href="?page={{i}}">{{i}}</a></li>
                {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                <li><a href="{% url 'blog:home' %}?page={{page_obj.next_page_number}}">&gt;</a></li>
                {% endif %}
              </ul>
            </div>

          </div><!-- End blog entries list -->

          {% include 'blog/sidebar.html' %}<!-- End blog sidebar -->

        </div>

      </div>
    </section><!-- End Blog Section -->

  </main>
{% endblock content %}

templates/blog/search.html
{% extends 'blog/base.html' %}
{% load static %}
{% load humanize %}

{% block content %}
    <main id="main">
    <!-- ======= Blog Section ======= -->
    <section class="breadcrumbs">
      <div class="container">

        <div class="d-flex justify-content-between align-items-center">
          <h2>Blog</h2>

          <ol>
            <li><a href="{% url 'website:web_home' %}">Home</a></li>
            <li>Blog-{{search}}</li>
          </ol>
        </div>

      </div>
    </section><!-- End Blog Section -->

    <!-- ======= Blog Section ======= -->
    <section id="blog" class="blog">
      <div class="container" data-aos="fade-up">

        <div class="row">

          <div class="col-lg-8 entries">
            {% for Article in Articles %}
            <article class="entry">

              <div class="entry-img">
                <img src="{{Article.thumbnail.url}}" alt="" class="img-fluid">
              </div>

              <h2 class="entry-title">
                <a href="{% url 'blog:single' slug=Article.slug %}">{{ Article.title }}</a>
                {% if Article.is_special %}
                  <span class="badge badge-danger">Special</span>
                {% endif %}
              </h2>

              <div class="entry-meta">
                <ul>
                  <li class="d-flex align-items-center"><i class="bi bi-person"></i> <a href="{% url 'blog:author' username=Article.Author.username %}">{{Article.Author.get_full_name}}</a></li>
                  <li class="d-flex align-items-center"><i class="bi bi-clock"></i> <a href="#"><time datetime="2020-01-01">{{ Article.created_date|naturaltime }}</time></a></li>
                  <li class="d-flex align-items-center"><i class="bi bi-chat-dots"></i> <a href="#">views: {{Article.hits.count}}</a></li>
                </ul>
              </div>

              <div class="entry-content">
                <p>
                  {{ Article.description|safe }}
                </p>
                <div class="read-more">
                  <a href="{% url 'blog:single' slug=Article.slug %}">Read More</a>
                </div>
              </div>
              {% for cat in Article.category.activ_cat %}
                <a href="{% url 'blog:category' slug=cat.slug %}"><div style="text-align-last: left;">#{{cat.title}}</div></a>
              {% endfor %}
            </article>
            {% endfor %}
            <div class="blog-pagination">
              <ul class="justify-content-center">
                {% if page_obj.has_previous %}
                <li><a href="{% url 'blog:search' page_obj.previous_page_number %}?q={{search}}">&lt;</a></li>
                {% endif %}
                {% for i in page_obj.paginator.page_range %}
                {% if page_obj.number == i %}
                  <li class="active"><a href="?page={{i}}">{{i}}</a></li>
                {% else %}
                  <li><a href="?page={{i}}">{{i}}</a></li>
                {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                <li><a href="{% url 'blog:search' page_obj.next_page_number %}?q={{search}}">&gt;</a></li>
                {% endif %}
              </ul>
            </div>

          </div><!-- End blog entries list -->

          {% include 'blog/sidebar.html' %}<!-- End blog sidebar -->

        </div>

      </div>
    </section><!-- End Blog Section -->

  </main>
{% endblock content %}